# Generated by Django 2.2 on 2019-07-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Comment',
        ),
    ]
